"use server";

import {
  contactFormSchema,
  type ContactFormData,
} from "@/schemas/contact-schema";
import {
  serverContactRepository,
  type ContactRecord,
} from "@/lib/contact-repository.server";

export interface ContactActionResult {
  success: boolean;
  message: string;
  data?: {
    id: string;
    createdAt: string;
    fullName: string;
    subject: string;
  };
  errors?: Record<string, string[]>;
}

/**
 * Server Action: submitContactFormAction
 *
 * 1. "use server" defines this as an RPC mutation endpoint generated by Next.js.
 * 2. It accepts raw unknown payload from the client.
 * 3. Never trusts client validation: passes raw payload through canonical Zod safeParse.
 * 4. Never exposes server secrets or raw stack traces.
 * 5. Sanitizes fields and saves into the server repository.
 * 6. Returns a strongly typed Action result contract.
 */
export async function submitContactFormAction(
  rawPayload: unknown
): Promise<ContactActionResult> {
  try {
    // 1. Strict Server-Side Validation: Never trust client input
    const parseResult = contactFormSchema.safeParse(rawPayload);

    if (!parseResult.success) {
      // Flatten Zod field errors into key-value error array
      const fieldErrors = parseResult.error.flatten().fieldErrors;
      return {
        success: false,
        message: "Server rejected payload: validation constraints not satisfied.",
        errors: fieldErrors,
      };
    }

    // 2. Data Sanitization & Normalization
    const validData: ContactFormData = {
      fullName: parseResult.data.fullName.trim(),
      email: parseResult.data.email.trim().toLowerCase(),
      phone: parseResult.data.phone.trim(),
      subject: parseResult.data.subject.trim(),
      message: parseResult.data.message.trim(),
    };

    // 3. Server-side Mutation in local repository abstraction
    const savedRecord: ContactRecord = await serverContactRepository.save(validData);

    // 4. Return sanitized, non-sensitive projection to the client
    return {
      success: true,
      message: `Inquiry successfully processed and registered with ID: ${savedRecord.id}.`,
      data: {
        id: savedRecord.id,
        createdAt: savedRecord.createdAt,
        fullName: savedRecord.fullName,
        subject: savedRecord.subject,
      },
    };
  } catch {
    // Catch unexpected exceptions without leaking system internals
    return {
      success: false,
      message: "An internal server error occurred while processing the mutation.",
    };
  }
}
